In [22]:
import numpy as np

#Array Creation

empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)

ones_array = np.ones((4, 2))
print("\n2. 4x2 array with all ones")
print(ones_array)

f_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print("\n3. Array filled with value 7:")
print(f_array)

zeros_like_array = np.zeros_like(ones_array)
print("\n4. Zeros array with same shape as ones_array:")
print(zeros_like_array)

ones_like_array = np.ones_like(f_array)
print("\n5. Ones array with same shape as filled_array:")
print(ones_like_array)

new_list = [1, 2, 3, 4]
list_to_array = np.array(new_list)
print("\n6. List converted to numpy array:")
print(list_to_array)




1. Empty 2x2 array:
[[2.5e-323 1.5e-323]
 [9.9e-324 4.9e-324]]

2. 4x2 array with all ones
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as ones_array:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones array with same shape as filled_array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List converted to numpy array:
[1 2 3 4]


In [23]:
#Array Manipulation

#  Array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr_range)

# Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:")
print(matrix_3x3)

# Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:")
print(identity_matrix)

# Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"\n4. Random array mean: {mean_value}")

# Create a 10X10 array with random values and find minimum and maximum
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print(f"\n5. 10x10 array - Min: {min_val}, Max: {max_val}")

# Array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (0-indexed)
print("\n6. Zero array with 5th element replaced:")
print(zero_array)

# Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. Border array (1 on border, 0 inside):")
print(border_array)

# Create a 8X8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print("\n9. 8x8 Checkerboard pattern:")
print(checkerboard)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean: 0.4467834559544944

5. 10x10 array - Min: 0.002761995151055796, Max: 0.99401711618674

6. Zero array with 5th element replaced:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
[0 4 0 0 2 1]

8. Border array (1 on border, 0 inside):
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
#Array Operation

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Arrays:")
print(f"x = {x}")
print(f"y = {y}")
print(f"v = {v}")
print(f"w = {w}")

# 1. Add the two arrays
add_xy = x + y
print("\n1. x + y:")
print(add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. x - y:")
print(sub_xy)

# 3. Multiply array with integer
mult_x = x * 3
print("\n3. x * 3:")
print(mult_x)

# 4. Square of each element
square_x = x ** 2
print("\n4. Square of x:")
print(square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print(f"\n5. Dot products:")
print(f"v · w = {dot_vw}")
print(f"x · v = {dot_xv}")
print(f"x · y = {dot_xy}")

# 6. Concatenation
concat_row = np.concatenate((x, y), axis=0)
concat_col_vw = np.vstack((v, w))  # Stack along rows to make column

print("\n6. Concatenation:")
print("x and y along rows:")
print(concat_row)
print("v and w along columns (using vstack):")
print(concat_col_vw)

# 7. Concatenate x and v (this will cause an error)
try:
    concat_xv = np.concatenate((x, v))
    print("Concatenation successful (unexpected)")
except ValueError as e:
    print(f"\n7. Error concatenating x and v: {e}")
    print("Explanation: Cannot concatenate arrays with different dimensions (2D vs 1D)")

Arrays:
x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. x + y:
[[ 6  8]
 [10 13]]

2. x - y:
[[-4 -4]
 [-4 -3]]

3. x * 3:
[[ 3  6]
 [ 9 15]]

4. Square of x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y = [[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns (using vstack):
[[ 9 10]
 [11 12]]

7. Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate arrays with different dimensions (2D vs 1D)


In [25]:
#Matrix Operations

# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrices A and B:")
print(f"A = {A}")
print(f"B = {B}")

# Q 1: Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_proof = np.dot(A, A_inv)
print("\n1. Proof that A.A⁻¹ = I:")
print("A.A⁻¹ =")
print("Approximate Identity matrix:", identity_proof)


# 2. Prove AB ≠ BA

#Dot product
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. Proof that AB ≠ BA:")
print(f"AB = {AB}")
print(f"BA = {BA}")
print(f"Are they equal? {np.array_equal(AB, BA)}")

# 3. Prove (AB)^T = B^T*A^T
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("\n3. Proof that (AB)ᵀ = BᵀAᵀ:")
print(f"(AB)ᵀ = {AB_transpose}")
print(f"BᵀAᵀ = {B_transpose_A_transpose}")
print(f"Are they equal? {np.array_equal(AB_transpose, B_transpose_A_transpose)}")

# Solve system of linear equations
print("\n" + "="*50)
print("SOLVING SYSTEM OF LINEAR EQUATIONS")
print("="*50)

# System:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

print("\nSOLVING SYSTEM OF LINEAR EQUATIONS")

print("Coefficient matrix A:\n", A)
print("Constant vector B:\n", B)

# Method 1: np.linalg.solve
sol_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve():")
print(f"x = {sol_solve[0]:.2f}, y = {sol_solve[1]:.2f}, z = {sol_solve[2]:.2f}")

# Method 2: Inverse method
sol_inv = np.linalg.inv(A).dot(B)
print("\nSolution using inverse method:")
print(f"x = {sol_inv[0]:.2f}, y = {sol_inv[1]:.2f}, z = {sol_inv[2]:.2f}")

# Verification
verification = A.dot(sol_solve)
print("\nVerification (A * solution):")
print(verification)
print("Original B:", B)
print("Close enough?", np.allclose(verification, B))

Matrices A and B:
A = [[3 4]
 [7 8]]
B = [[5 3]
 [2 1]]

1. Proof that A.A⁻¹ = I:
A.A⁻¹ =
Approximate Identity matrix: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Proof that AB ≠ BA:
AB = [[23 13]
 [51 29]]
BA = [[36 44]
 [13 16]]
Are they equal? False

3. Proof that (AB)ᵀ = BᵀAᵀ:
(AB)ᵀ = [[23 51]
 [13 29]]
BᵀAᵀ = [[23 51]
 [13 29]]
Are they equal? True

SOLVING SYSTEM OF LINEAR EQUATIONS

SOLVING SYSTEM OF LINEAR EQUATIONS
Coefficient matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constant vector B:
 [-1 -3  9]

Solution using np.linalg.solve():
x = 2.00, y = 1.00, z = -2.00

Solution using inverse method:
x = 2.00, y = 1.00, z = -2.00

Verification (A * solution):
[-1. -3.  9.]
Original B: [-1 -3  9]
Close enough? True
